Firstname        = input("Enter the Firstname :")
Lastname         = input("Enter the Lastname :")
Contact          = int(input("Enter a Contact:"))
Email            = input("Enter the Email :") 
Objective        = input("Enter the Objective :")
Technicalsummary = input("Enter the Technical Summary :")
Technicalsummary2 = input("Enter the Technical Summary :")
Technicalsummary3 = input("Enter the Technical Summary :")
Technicalsummary4 = input("Enter the Technical Summary :")
Technicalsummary5 = input("Enter the Technical Summary :")
Domain           = input("Enter a Domain :")
Tools            = input("Enter a Tools :")
Languages        = input("Enter a Languages :")
Frameworks       = input("Enter a FrameWorks :")
OS               = input("Enter a OS :")
Coursecompleted  = input("Enetr  the Course Completed :")
Education        = input("Enter the  Education :")
HSC              = input("Enter a HSC :")
SSLC             = input("Enter a SSLC :")
Project          = input("Enter the Project :")
Project1          = input("Enter the Project :")
print("--------------------------------------------------------------------------------------------------------"*1)
print("\t\t\t\tResume")
print("--------------------------------------------------------------------------------------------------------"*1)
print()
print(Firstname.upper(),Lastname.upper(),"\n")
print("Contact  : ",Contact,"\n")
print("Email    : ",Email)
print()
print("OBJECTIVES")
print("--------------------------------------------------------------------------------------------------------"*1)
print()
print(Objective)
print()
print("TECHNICAL SUMMARY")
print("--------------------------------------------------------------------------------------------------------"*1)
print()
print(Technicalsummary,"\n")
print(Technicalsummary2,"\n")
print(Technicalsummary3,"\n")
print(Technicalsummary4,"\n")
print(Technicalsummary5,"\n")
print()
print("TECHNICAL SKILLS")
print("--------------------------------------------------------------------------------------------------------"*1)
print()
print("Domain       :",Domain,"\n")
print("Tools        :  ",Tools,"\n")
print("Languagues   :",Languages,"\n")
print("FrameWorks   :",Frameworks,"\n")
print("OS           :",OS,"\n")
print()
print("COURSE COMPLETED")
print("----------------------------------------------------------------------------------------------------------"*1)
print(Coursecompleted)
print()
print("ACADEMIC QUALIFICATION")
print("-----------------------------------------------------------------------------------------------------------"*1)
print(Education,"\n")
print(HSC,"\n")
print(SSLC,"\n")
print()
print("ACADEMIC PROJECT")
print("-----------------------------------------------------------------------------------------------------------"*1)
print(Project,"\n")
print("\t\t\t\t\t",Project1)
print("-----------------------------------------------------------------------------------------------------------"*1)